apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdo-owner-services-deployment
  namespace: openhorizon
  labels:
    app: open-horizon
    component: sdo-owner-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-horizon
      component: sdo-owner-services
  template:
    metadata:
      labels:
        app: open-horizon
        component: sdo-owner-services
    spec:
      securityContext:
        runAsUser: 1000620000
        runAsGroup: 1000620000
        fsGroup: 1000620000
      restartPolicy: Always
      containers:
        - name: sdo-owner-services
          image: openhorizon/sdo-owner-services:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HZN_EXCHANGE_URL
              value: http://exchange.openhorizon.svc.cluster.local:3090/v1
            - name: EXCHANGE_INTERNAL_URL
              value: http://exchange-api:8080/v1
            - name: HZN_FSS_CSSURL
              value: https://css.openhorizon.svc.cluster.local:9443/
            - name: HZN_ORG_ID
              value: IBM
            - name: SDO_OWNER_SVC_HOST
              value: 0.0.0.0
            - name: SDO_OCS_API_PORT
              value: "9008"
            - name: SDO_RV_PORT
              value: "8040"
            - name: SDO_OPS_PORT
              value: "8042"
            - name: SDO_OPS_EXTERNAL_PORT
              value: "8042"
            - name: SDO_OCS_DB_PATH
              value: /home/sdouser/ocs/config/db
            - name: SDO_GET_PKGS_FROM
              value: ${SDO_GET_PKGS_FROM}
          volumeMounts:
            - name: ocsdb
              mountPath: /home/sdouser/ocs/config/db
            - name: hzn-cert
              mountPath: /home/sdouser/ocs-api-dir/keys
              readOnly: true
          livenessProbe:
            exec:
              command:
                - "test $$(curl -sS -w %{http_code} -o /dev/null -X POST http://localhost:8040/mp/113/msg/20) -eq 200"
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 15
      volumes:
        - name: ocsdb
          persistentVolumeClaim:
            claimName: sdo-pvc
        - name: hzn-cert
          secret:
            secretName: horizon-mgmt-hub
            items: 
              - key: tls.crt
                path: "horizonMgmtHub.crt"
              - key: tls.key
                path: "horizonMgmtHub.key"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: sdo-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sdo-service
spec:
  selector:
    app: open-horizon
    component: sdo
  ports:
    - name: sdo-rv-port
      protocol: TCP
      port: 8040
      targetPort: 8040
    - name: sdo-ocs-api-port
      protocol: TCP
      port: 9008
      targetPort: 9008
    - name: sdo-ops-port
      protocol: TCP
      port: 8042
      targetPort: 8042

# sdo-owner-services:
#   image: ${SDO_IMAGE_NAME}:${SDO_IMAGE_TAG}
#   container_name: sdo-owner-services
#   restart: always
#   ports:
#     - ${HZN_LISTEN_IP}:${SDO_OCS_API_PORT}:${SDO_OCS_API_PORT}
#     - ${HZN_LISTEN_IP}:${SDO_RV_PORT}:${SDO_RV_PORT}
#     - ${HZN_LISTEN_IP}:${SDO_OPS_EXTERNAL_PORT}:${SDO_OPS_PORT}
#   networks:
#     - horizonnet
#   volumes:
#     - ocsdb:${SDO_OCS_DB_PATH}
#     # deploy-mgmt-hub.sh will ensure this dir is empty if we want to use http
#     - ${CERT_DIR}:/home/sdouser/ocs-api-dir/keys:${VOLUME_MODE}
#   # intentionally omitting HZN_MGMT_HUB_CERT from the environment section, since we use http in this environment
#   environment:
#     - HZN_EXCHANGE_URL=http://${HZN_LISTEN_IP}:${EXCHANGE_PORT}/v1
#     - EXCHANGE_INTERNAL_URL=http://exchange-api:8080/v1
#     - HZN_FSS_CSSURL=${HZN_TRANSPORT}://${HZN_LISTEN_IP}:${CSS_PORT}/
#     - HZN_ORG_ID=${EXCHANGE_USER_ORG}
#     - SDO_OWNER_SVC_HOST=${HZN_LISTEN_IP}
#     - SDO_OCS_API_PORT=${SDO_OCS_API_PORT}
#     - SDO_RV_PORT=${SDO_RV_PORT}
#     - SDO_OPS_PORT=${SDO_OPS_PORT}
#     - SDO_OPS_EXTERNAL_PORT=${SDO_OPS_EXTERNAL_PORT}
#     - SDO_OCS_DB_PATH=${SDO_OCS_DB_PATH}
#     - SDO_GET_PKGS_FROM=${SDO_GET_PKGS_FROM}
#   healthcheck:
#     test: test $$(curl -sS -w %{http_code} -o /dev/null -X POST http://localhost:${SDO_RV_PORT}/mp/113/msg/20) -eq 200
#     interval: 15s
#     timeout: 5s
#     retries: 3
#   depends_on:
#     - exchange-api
  